set-option -g prefix C-Space

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi
set -g mouse off
set -g history-limit 2000

set-option -g default-shell /opt/homebrew/bin/fish

# Keymaps
bind -r r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
bind -r F run-shell "tmux neww ~/.config/tmux/custom_scripts/sessionizer.bash"

# Move across panes easily
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Colors
set -g status-style "fg=white,bg=color236"
set -g message-style "fg=white,bold,bg=color236"
set -g mode-style "fg=white,bold,bg=color236"

