#!/usr/bin/env bash

project_dir=`printf "$(find -L "$HOME" -path "$HOME/Library" -prune -o -type d -print)" | fzf`
project_name=`basename $project_dir`

tmux has-session -t $project_name 2>/dev/null

if [ $? != 0 ]; then
    # Set up your session
    tmux new -c "$project_dir" -s "$project_name" -d "nvim"
    tmux neww -t "$project_name" -c "$project_dir"
fi

if [[ "$project_name" =~ \. ]]; then
    tmux attach-session -t "_${project_name##*\.}" 
    tmux switch -t "_${project_name##*\.}" 
else
    # Attach to created session
    tmux attach-session -t "${project_name}:1"
    tmux switch -t "${project_name}:1"
fi



