set-option -g prefix C-Space

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi
set -g mouse on
set -g history-limit 2000

set-option -g default-shell /bin/zsh

# Keymaps
bind -r r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
bind -r F run-shell "tmux neww ~/.config/tmux/custom_scripts/sessionizer.bash"

# Move across panes easily
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Colors
set -g status-style "fg=white,bg=color234"
# set -g message-style "fg=white,bold,bg=color236"
# set -g mode-style "fg=white,bold,bg=color236"

unbind C-e
bind -n C-e send-keys C-e

unbind C-a
bind -n C-a send-keys C-a

# Status bar (george hotz)
set -g status-left ' '
set -g status-right "#[bg=color243,fg=black,bold] %d/%m #[bg=color247] %H:%M "

set -g window-status-format "#[fg=colour143]#I#[fg=colour243]:#[fg=grey]#W#{?window_active,,#[fg=colour243]-} "
set -g window-status-current-format "#[fg=colour143]#I#[fg=colour231]:#W#[fg=cyan]* "

